spring:
  application:
    name: springdatajpa

  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: chill
    password: chill
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true